dummydata/urls.py
from django.urls import path

from .views import (
    FakeSchemaListView,
    FakeSchemaCreate,
    FakeSchemaEdit,
    DataSetsView,
    Login,
    SchemaDelete,
)

urlpatterns = [
    path("", Login.as_view(), name="index"),
    path("schemas/", FakeSchemaListView.as_view(), name="schema-list"),
    path("schemas/create/", FakeSchemaCreate.as_view(), name="schema-create"),
    path(
        "schemas/edit/<int:pk>/", FakeSchemaEdit.as_view(), name="schema-edit"
    ),
    path(
        "schemas/delete/<int:pk>/",
        SchemaDelete.as_view(),
        name="schema-delete",
    ),
    path("schemas/<int:pk>/", DataSetsView.as_view(), name="schema-detail"),
]
app_name = "dummydata"

fake_csv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dummydata.urls", namespace="dummydata")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="">
        FakeCSV
      </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dummydata:schema-list' %}">Schemas</a>
        </li>
      </ul>
    </div>
    {% if user.is_authenticated %}
    <div class="dropdown">
      <a class="nav-link dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
        Hello, {{ user.username }}
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
        <li>
          <a class="dropdown-item text-danger" href="{% url 'logout' %}">Logout <i class="bi bi-box-arrow-in-right"></i></a>
        </li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
<ul class="pagination mt-3">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a href="?page=1" class="page-link"><i class="fas fa-fast-backward"></i></a>
  </li>
  <li class="page-item">
    <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="fas fa-backward"></i></a>
  </li>
  {% endif %}
  <li class="page-item active">
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
  </li>
  {% if page_obj.has_next %}
  <li class="page-item">
    <a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fas fa-forward"></i></a>
  </li>
  <li class="page-item">
    <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link"><i class="fas fa-fast-forward"></i></a>
  </li>
  {% endif %}
</ul>
{% endif %}