dummydata/urls.py
from django.urls import path

from .views import (
    FakeSchemaListView,
    FakeSchemaCreate,
    FakeSchemaEdit,
    DataSetsView,
    Login,
    SchemaDelete,
)

urlpatterns = [
    path("", Login.as_view(), name="index"),
    path("schemas/", FakeSchemaListView.as_view(), name="schema-list"),
    path("schemas/create/", FakeSchemaCreate.as_view(), name="schema-create"),
    path(
        "schemas/edit/<int:pk>/", FakeSchemaEdit.as_view(), name="schema-edit"
    ),
    path(
        "schemas/delete/<int:pk>/",
        SchemaDelete.as_view(),
        name="schema-delete",
    ),
    path("schemas/<int:pk>/", DataSetsView.as_view(), name="schema-detail"),
]
app_name = "dummydata"

fake_csv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dummydata.urls", namespace="dummydata")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dummydata/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class FakeSchema(models.Model):

    DELIMITERS = [
        (",", "Comma(,)"),
        (";", "Semilicon(;)"),
        ("\t", "Tab(\t)"),
        (" ", "Space( )"),
        ("|", "Pipe(|)"),
    ]

    QUOTES = [
        ('"', 'Double-quote(")'),
        ("'", "Single-quote(')"),
    ]

    title = models.CharField(max_length=63, blank=True, null=True)
    column_separator = models.TextField(
        choices=DELIMITERS, default=",", max_length=1
    )
    string_character = models.TextField(
        choices=QUOTES, default='""', max_length=1
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="schemas"
    )

    def get_absolute_url(self):
        return reverse("dummydata:schema-detail", kwargs={"pk": self.id})

    class Meta:
        ordering = ["-updated"]


class FakeSchemaColumn(models.Model):

    DATA_TYPES = [
        ("Full_name", "Full name (a combination of first name and last name)"),
        ("Job", "Job"),
        ("Email", "Email"),
        ("Domain", "Domain name"),
        ("Phone", "Phone number"),
        ("Company", "Company name"),
        ("Text", "Text (with a specified range for a number of sentences)"),
        ("Integer", "Integer (with specified range)"),
        ("Address", "Address"),
        ("Date", "Date"),
    ]

    column_name = models.CharField(max_length=20)
    data_type = models.CharField(max_length=20, choices=DATA_TYPES)
    order = models.PositiveIntegerField(default=0)
    schema = models.ForeignKey(
        FakeSchema, on_delete=models.CASCADE, related_name="schemacolumns"
    )

    class Meta:
        ordering = ["order"]

    def clean(self):
        super(FakeSchemaColumn, self).clean()
        if not self.order:
            self.order = (
                FakeSchemaColumn.objects.filter(schema=self.schema).count() + 1
            )


class DataSet(models.Model):
    STATUSES = [(0, "Processing.."), (1, "Ready!")]
    schema = models.ForeignKey(
        FakeSchema, on_delete=models.CASCADE, related_name="schemadatasets"
    )
    created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUSES, default=0)
    rows = models.PositiveIntegerField(null=True)
    download_link = models.URLField()

    class Meta:
        ordering = ["-created"]

dummydata/forms.py
from django import forms
from extra_views import InlineFormSetFactory

from dummydata.models import FakeSchema, FakeSchemaColumn, DataSet


class FakeSchemaForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Write name of schema"})
    )

    class Meta:
        model = FakeSchema
        fields = "__all__"
        widgets = {"author": forms.HiddenInput()}


class FakeCSVSchemaColumnForm(forms.ModelForm):
    column_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Write column name"}),
    )

    class Meta:
        model = FakeSchemaColumn
        fields = "__all__"


class FakeCSVSchemaColumnInline(InlineFormSetFactory):
    model = FakeSchemaColumn
    form_class = FakeCSVSchemaColumnForm

    fields = "__all__"

    factory_kwargs = {
        "extra": 1,
        "max_num": None,
        "can_order": False,
        "can_delete": True,
    }


class DataSetForm(forms.ModelForm):
    class Meta:
        model = DataSet
        fields = ("rows",)

dummydata/views.py
import sweetify
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormMixin
from extra_views import CreateWithInlinesView, UpdateWithInlinesView
from .generator import generate_csv_file

from dummydata.forms import (
    FakeSchemaForm,
    FakeCSVSchemaColumnInline,
    DataSetForm,
)
from dummydata.models import FakeSchema, DataSet


class Login(LoginView):
    template_name = "registration/login.html"
    redirect_authenticated_user = True


class FakeSchemaListView(LoginRequiredMixin, generic.ListView):
    model = FakeSchema
    queryset = FakeSchema.objects.all()
    paginate_by = 5
    template_name = "dummydata/schemalist.html"

    def get_queryset(self):
        return self.queryset.filter(author=self.request.user)


class FakeSchemaCreate(LoginRequiredMixin, CreateWithInlinesView):
    model = FakeSchema
    form_class = FakeSchemaForm
    inlines = [
        FakeCSVSchemaColumnInline,
    ]
    template_name = "dummydata/schema-form.html"

    def get_initial(self):
        return {"author": self.request.user}

    def get_success_url(self):
        if "action" in self.request.POST:
            if self.request.POST["action"] == "add_column":
                return reverse_lazy(
                    "dummydata:schema-edit", kwargs={"pk": self.object.pk}
                )
            if self.request.POST["action"] == "submit":
                return reverse_lazy("dummydata:schema-list")
        return reverse_lazy("dummydata:schema-list")


class FakeSchemaEdit(
    LoginRequiredMixin, UserPassesTestMixin, UpdateWithInlinesView
):
    model = FakeSchema
    form_class = FakeSchemaForm
    inlines = [
        FakeCSVSchemaColumnInline,
    ]
    template_name = "dummydata/schema-form.html"

    def get_success_url(self):
        if "action" in self.request.POST:
            if self.request.POST["action"] == "add_column":
                return reverse_lazy(
                    "dummydata:schema-edit", kwargs={"pk": self.object.pk}
                )
            if self.request.POST["action"] == "submit":
                return reverse_lazy("dummydata:schema-list")
        return reverse_lazy("dummydata:schema-list")

    def test_func(self):
        schema = self.get_object()
        return schema.author == self.request.user


class SchemaDelete(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = FakeSchema

    def get_success_url(self):
        sweetify.success(self.request, "Schema was deleted")
        return reverse_lazy("dummydata:schema-list")

    def test_func(self):
        schema = self.get_object()
        return schema.author == self.request.user


def is_ajax(request):
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


class DataSetsView(
    LoginRequiredMixin, UserPassesTestMixin, FormMixin, generic.DetailView
):
    model = FakeSchema
    form_class = DataSetForm
    template_name = "dummydata/datasets.html"

    def test_func(self):
        schema = self.get_object()
        return schema.author == self.request.user

    def get_context_data(self, **kwargs):
        context = super(DataSetsView, self).get_context_data()
        schema = self.get_object()
        columns = schema.schemacolumns.all()
        context["columns"] = columns
        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        schema = self.get_object()
        dataset = DataSet.objects.create(
            schema=schema, rows=int(request.POST["rows"])
        )

        if is_ajax(request):

            generate_csv_file(dataset)

            html = render_to_string(
                "dummydata/table.html",
                context={"fakeschema": schema},
                request=request,
            )

            return JsonResponse({"msg": html})

        return HttpResponseRedirect(
            reverse_lazy("dummydata:schema-detail", kwargs={"pk": schema.pk})
        )

templates/dummydata/datasets.html
{% extends 'base.html' %} {% load crispy_forms_filters %} {% block content %}

<h1>Data sets of {{ fakeschema.title }}
<a href="{% url 'dummydata:schema-list'%}" class="btn btn-link">Back</a>
</h1>
{% if columns %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Column name</th>
      <th scope="col">Data type</th>
    </tr>
  </thead>

  <tbody>
  {% for column in columns %}



    <tr>
      <th>{{ column.column_name }}</th>
      <td>{{ column.data_type }}</td>

    </tr>

    {% endfor %}
  </tbody>
</table>
  {% else %}
  <p class="lead">No columns</p>
{% endif %}


<form method="post" id="upload_form">
  {% csrf_token %}

  {{ form.rows|as_crispy_field }}

  <button type="submit" class="btn btn-success" id="click-me" >Generate data</button>
</form>
<hr />
{% if fakeschema.schemadatasets.count == 0 %}
<p>No datasets yet.</p>
{%else%}
  <div id="datasets">
    {% include 'dummydata/table.html'%}
  </div>
{% endif %}
  <script>
  $(document).ready(function (){

         $(document).on('submit','#upload_form', function(e){
         e.preventDefault();

           $.ajax({
                type : "POST",
                url: "{% url 'dummydata:schema-detail' fakeschema.pk%}",
                data: {
                 rows : $('#id_rows').val(),
                 csrfmiddlewaretoken: '{{ csrf_token }}',
                 dataType: "json",

                },

                success: function(data){

                    $(`#datasets`).html(data["msg"])
                    document.getElementById("upload_form").reset()
                },

            });
                 });
  })
      </script>
{% endblock %}

templates/dummydata/fakeschema_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete {{ fakeschema.title }}</h1>
<p class="lead">Are you sure you want to delete this schema?</p>
<form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Yes, delete">
  <a href="{% url 'dummydata:schema-list' %}">
  <input class="btn btn-secondary" value="Cancel">
  </a>
</form>
{% endblock %}

templates/dummydata/schema-form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block title %}<title>{{ object|yesno:"Update,Add" }} schema</title>{% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
  <h1>{{ object|yesno:"Update,New" }} schema {% if fakeschema %}{{ fakeschema.title }}{% endif %}
    <a href="{% url 'dummydata:schema-list'%}" class="btn btn-link">Back</a>
  </h1>
<button type="submit" name="action" value="submit" class="btn btn-success">Submit</button>

  {% csrf_token %} {{ form|crispy }}
  <div style="margin-top: 20px;">
    <h3>Schema columns</h3>
    {% for formset in inlines %}
    <div class="formset">
      {{ formset.management_form|crispy}} {% for columnsform in formset %}
      <div class="row flex-nowrap row-cols-lg-auto g-3 align-items-center">
        {{ columnsform|crispy }}
      </div>
      {% if forloop.last %}
      <div>
        <button class="btn btn-success" type="submit" name="action" value="add_column">Add column</button>
      </div>
      {% endif %} {% endfor %}
    </div>
  </div>
  {% endfor %}
</form>
{% endblock %}

templates/dummydata/schemalist.html
{% extends "base.html" %} {% block title %}
<title>Schema list</title>
{% endblock %} {% block content %}

<h1>
  Data schemas

  <a class="btn btn-success" href="{% url 'dummydata:schema-create' %}">
    Create Schema
    <i class="fas fa-plus"></i>
  </a>
</h1>
{% if fakeschema_list %}
<table class="table table-strip table-bordered text-center bg-white">
  <thead class="table-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Modified</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  {% for fakeschema in fakeschema_list %}
  <tbody>
    <tr class="text-dark">
      <td>{{ forloop.counter }}</td>
      <td>
        <a class="btn btn-link" href="{{ fakeschema.get_absolute_url }}"> {{ fakeschema.title}}</a>
      </td>
      <td>
        {% if fakeschema.updated %} {{ fakeschema.updated }} {% else %} {{ fakeschema.created }} {% endif %}
      </td>
      <td>
        <a class="btn btn-success" href="{% url 'dummydata:schema-edit' pk=fakeschema.id%}"> <i class="far fa-edit"></i></a>
        <a class="btn btn-danger" href="{% url 'dummydata:schema-delete' pk=fakeschema.id%}"> <i class="far fa-trash-alt"></i></a>
      </td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% else %}
<p>There is no schemas :(</p>
{% endif %} {% endblock %}

templates/dummydata/table.html
<table class="table table-strip table-bordered text-center bg-white" id="table">
  <thead class="table-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Created</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for dataset in fakeschema.schemadatasets.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ dataset.created }}</td>
      <td>
        {% if dataset.status == 1 %}
        <span class="badge badge-success">Success</span>
        {%else%}
        <span class="badge badge-danger">Processing</span>
        {%endif%}
      </td>

      <td>
        <a href="{{dataset.download_link}}" class="btn btn-link">Download</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>